/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    'instance-watcher adapter settings': {
        en: 'Adapter settings for instance-watcher',
        de: 'Adaptereinstellungen für instance-watcher',
        ru: 'Настройки адаптера для instance-watcher',
        pt: 'Configurações do adaptador para instance-watcher',
        nl: 'Adapterinstellingen voor instance-watcher',
        fr: "Paramètres d'adaptateur pour instance-watcher",
        it: "Impostazioni dell'adattatore per instance-watcher",
        es: 'Ajustes del adaptador para instance-watcher',
        pl: 'Ustawienia adaptera dla instance-watcher',
        'zh-cn': 'instance-watcher的适配器设置',
    },
    option1: {
        en: 'option1',
        de: 'Option 1',
        ru: 'Опция 1',
        pt: 'Opção 1',
        nl: 'Optie 1',
        fr: 'Option 1',
        it: 'opzione 1',
        es: 'Opción 1',
        pl: 'opcja 1',
        'zh-cn': '选项1',
    },
    option2: {
        en: 'option2',
        de: 'Option 2',
        ru: 'вариант 2',
        pt: 'opção 2',
        nl: 'Optie 2',
        fr: 'Option 2',
        it: 'opzione 2',
        es: 'opcion 2',
        pl: 'Opcja 2',
        'zh-cn': '选项2',
    },
};
